drop table IF EXISTS vendors CASCADE;
drop table IF EXISTS hd CASCADE;
drop table IF EXISTS laptops CASCADE;
drop table IF EXISTS monitors CASCADE;
drop table IF EXISTS pc CASCADE;

create TABLE IF NOT EXISTS vendors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id)
);

create table if not exists hd(
    id bigint generated by default as identity not null constraint hd_pk primary key,
    vendor_id bigint not null constraint hd_vendors_id_fk references vendors
        on update cascade on delete cascade,
    numbers bigint,
    price bigint,
    count bigint,
    sizes Integer,
    item_type VARCHAR(512)
);


create table if not exists laptops(
    id bigint generated by default as identity not null constraint laptop_pk primary key,
    vendor_id bigint not null constraint laptops_vendors_id_fk references vendors
        on update cascade on delete cascade,
    numbers bigint,
    price bigint,
    count bigint,
    sizes integer,
    item_type VARCHAR(512)
);

create table if not exists monitors(
    id bigint generated by default as identity not null constraint monitors_pk primary key,
    vendor_id bigint not null constraint monitors_vendors_id_fk references vendors
        on update cascade on delete cascade,
    numbers bigint,
    price bigint,
    count bigint,
    sizes integer,
    item_type VARCHAR(512)
);

create table if not exists pc(
    id bigint generated by default as identity not null constraint pc_pk primary key,
    vendor_id bigint not null constraint pc_vendors_id_fk references vendors
        on update cascade on delete cascade,
    numbers bigint,
    price bigint,
    count bigint,
    pcForms varchar(512),
    item_type VARCHAR(512)
);
